#!/usr/bin/env python3
"""
Data Loading Module for Enhanced Research Visualization Pipeline

This module provides functions to load analysis results from CSV files
generated by the advanced systematic analyzer for visualization purposes.
"""

import pandas as pd
from pathlib import Path
from typing import Tuple
from loguru import logger


def load_analysis_data() -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """
    Load comprehensive analysis data from the most recent CSV files.
    
    This function automatically finds and loads the latest analysis results
    from the results directory, including comprehensive analysis, selection
    summary, and selected representatives data.
    
    Returns:
        Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]: A tuple containing:
            - df_all: Complete analysis data for all papers (3735 papers)
            - df_summary: Topic-level summary statistics (56 topics)
            - df_selected: Selected representative papers (533 papers)
    
    Raises:
        FileNotFoundError: If any required analysis files are missing
        ValueError: If loaded data has unexpected structure or content
    
    Example:
        >>> df_all, df_summary, df_selected = load_analysis_data()
        >>> print(f"Loaded {len(df_all)} papers, {len(df_selected)} representatives")
        Loaded 3735 papers, 533 representatives
    
    Note:
        - Automatically selects the most recent files based on modification time
        - Validates data integrity and structure after loading
        - Provides comprehensive logging for transparency
        - Expected file patterns: comprehensive_analysis_*.csv, selection_summary_*.csv, selected_representatives_*.csv
    """
    # Find the most recent analysis files
    results_dir = Path("results")
    
    if not results_dir.exists():
        raise FileNotFoundError(f"Results directory not found: {results_dir}")
    
    # Load comprehensive analysis
    comprehensive_files = list(results_dir.glob("comprehensive_analysis_*.csv"))
    if not comprehensive_files:
        raise FileNotFoundError("No comprehensive analysis files found in results directory")
    
    latest_comprehensive = max(comprehensive_files, key=lambda x: x.stat().st_mtime)
    logger.info(f"📂 Loading comprehensive analysis from: {latest_comprehensive.name}")
    df_all = pd.read_csv(latest_comprehensive)
    
    # Load selection summary
    summary_files = list(results_dir.glob("selection_summary_*.csv"))
    if not summary_files:
        raise FileNotFoundError("No selection summary files found in results directory")
    
    latest_summary = max(summary_files, key=lambda x: x.stat().st_mtime)
    logger.info(f"📂 Loading selection summary from: {latest_summary.name}")
    df_summary = pd.read_csv(latest_summary)
    
    # Load selected representatives
    selected_files = list(results_dir.glob("selected_representatives_*.csv"))
    if not selected_files:
        raise FileNotFoundError("No selected representatives files found in results directory")
    
    latest_selected = max(selected_files, key=lambda x: x.stat().st_mtime)
    logger.info(f"📂 Loading selected representatives from: {latest_selected.name}")
    df_selected = pd.read_csv(latest_selected)
    
    # Validate data integrity
    validate_loaded_data(df_all, df_summary, df_selected)
    
    logger.info(f"✅ Analysis data loaded successfully:")
    logger.info(f"   📊 All papers: {len(df_all):,}")
    logger.info(f"   📊 Selected representatives: {len(df_selected):,}")
    logger.info(f"   📊 Topics: {len(df_summary)}")
    
    return df_all, df_summary, df_selected


def validate_loaded_data(df_all: pd.DataFrame, df_summary: pd.DataFrame, df_selected: pd.DataFrame) -> None:
    """
    Validate the integrity and structure of loaded analysis data.
    
    This function performs comprehensive validation checks on the loaded
    DataFrames to ensure they have the expected structure and content
    for downstream visualization processing.
    
    Args:
        df_all: Complete analysis DataFrame
        df_summary: Topic summary DataFrame  
        df_selected: Selected representatives DataFrame
    
    Raises:
        ValueError: If data validation fails
    
    Validation checks:
        - Required columns are present
        - Data types are appropriate
        - Value ranges are reasonable
        - Cross-DataFrame consistency
        - No critical missing values
    
    Example:
        >>> validate_loaded_data(df_all, df_summary, df_selected)
        # Raises ValueError if validation fails, otherwise passes silently
    
    Note:
        - Checks for presence of key columns needed for visualizations
        - Validates metric ranges (e.g., scores between 0-1)
        - Ensures consistency between datasets
        - Logs validation warnings for minor issues
    """
    # Check required columns in df_all
    required_all_columns = [
        'title', 'authors', 'topic_id', 'similarity_to_centroid', 
        'diversity_score', 'representativeness_score', 'is_selected_representative'
    ]
    
    missing_all = [col for col in required_all_columns if col not in df_all.columns]
    if missing_all:
        raise ValueError(f"Missing required columns in comprehensive analysis: {missing_all}")
    
    # Check required columns in df_summary
    required_summary_columns = [
        'topic_id', 'topic_name', 'cluster_size', 'papers_selected', 
        'selection_ratio', 'avg_centrality', 'avg_diversity'
    ]
    
    missing_summary = [col for col in required_summary_columns if col not in df_summary.columns]
    if missing_summary:
        raise ValueError(f"Missing required columns in selection summary: {missing_summary}")
    
    # Check required columns in df_selected
    required_selected_columns = [
        'title', 'authors', 'topic_id', 'similarity_to_centroid', 
        'diversity_score', 'representativeness_score'
    ]
    
    missing_selected = [col for col in required_selected_columns if col not in df_selected.columns]
    if missing_selected:
        raise ValueError(f"Missing required columns in selected representatives: {missing_selected}")
    
    # Validate data ranges
    if not (0 <= df_all['similarity_to_centroid'].min() <= df_all['similarity_to_centroid'].max() <= 1):
        logger.warning("Similarity to centroid values outside expected range [0,1]")
    
    if not (0 <= df_all['diversity_score'].min() <= df_all['diversity_score'].max() <= 1):
        logger.warning("Diversity score values outside expected range [0,1]")
    
    if not (0 <= df_all['representativeness_score'].min() <= df_all['representativeness_score'].max() <= 1):
        logger.warning("Representativeness score values outside expected range [0,1]")
    
    # Check consistency between datasets
    selected_count = len(df_selected)
    all_selected_count = len(df_all[df_all['is_selected_representative'] == True])
    
    if selected_count != all_selected_count:
        logger.warning(f"Selected representatives count mismatch: {selected_count} vs {all_selected_count}")
    
    # Check topic consistency
    unique_topics_all = set(df_all['topic_id'].unique())
    unique_topics_summary = set(df_summary['topic_id'].unique())
    
    if unique_topics_all != unique_topics_summary:
        logger.warning("Topic IDs mismatch between comprehensive analysis and summary")
    
    logger.info("✅ Data validation passed")


def get_data_summary(df_all: pd.DataFrame, df_summary: pd.DataFrame, df_selected: pd.DataFrame) -> dict:
    """
    Generate summary statistics for loaded analysis data.
    
    Args:
        df_all: Complete analysis DataFrame
        df_summary: Topic summary DataFrame
        df_selected: Selected representatives DataFrame
    
    Returns:
        dict: Summary statistics and metadata about the loaded data
    
    Example:
        >>> summary = get_data_summary(df_all, df_summary, df_selected)
        >>> print(f"Selection ratio: {summary['selection_ratio']:.2%}")
        Selection ratio: 14.27%
    
    Note:
        - Provides key statistics for visualization context
        - Includes data quality metrics
        - Used for dashboard summaries and reports
    """
    return {
        'total_papers': len(df_all),
        'selected_papers': len(df_selected),
        'total_topics': len(df_summary),
        'selection_ratio': len(df_selected) / len(df_all),
        'avg_cluster_size': df_summary['cluster_size'].mean(),
        'avg_papers_selected_per_topic': df_summary['papers_selected'].mean(),
        'papers_with_topics': len(df_all[df_all['topic_id'] != -1]),
        'outlier_papers': len(df_all[df_all['topic_id'] == -1]),
        'data_completeness': {
            'all_papers_complete': df_all.isnull().sum().sum() == 0,
            'summary_complete': df_summary.isnull().sum().sum() == 0,
            'selected_complete': df_selected.isnull().sum().sum() == 0
        }
    } 