[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "research_analysis"
version = "0.1.0"
description = "A unified framework for systematic bibliography analysis."
authors = [{ name = "Eduard", email = "your@email.com" }]
requires-python = ">=3.11"
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "bertopic",
    "bibtexparser",
    "loguru",
    "numpy",
    "pandas",
    "plotly",
    "pydantic",
    "pyyaml",
    "scikit-learn",
    "sentence-transformers",
    "typer[all]",
    "umap-learn",
    "hdbscan"
]

[project.scripts]
research-analysis = "research_analysis.main:app" 