#!/usr/bin/env python3
"""
Data loading module for Stage 3 visualization.

This module loads the artifacts generated by Stage 2 (paper selection)
for visualization and reporting purposes.
"""

from pathlib import Path
from typing import Tuple

import pandas as pd

from research_analysis.utils.logging import get_logger

logger = get_logger()


def load_stage_2_artifacts(stage_2_dir: Path) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """
    Load Stage 2 paper selection artifacts for visualization.
    
    Args:
        stage_2_dir: Directory containing Stage 2 output files
        
    Returns:
        Tuple containing:
        - comprehensive_analysis: Complete analysis of all papers
        - selection_summary: Topic-level summary statistics  
        - selected_representatives: Only the selected representative papers
        
    Raises:
        FileNotFoundError: If required Stage 2 files are missing
        ValueError: If loaded data has invalid structure
    """
    logger.info(f"Loading Stage 2 artifacts from: {stage_2_dir}")
    
    # Define expected file paths
    comprehensive_path = stage_2_dir / "comprehensive_analysis.csv"
    summary_path = stage_2_dir / "selection_summary.csv"
    selected_path = stage_2_dir / "selected_representatives.csv"
    
    # Check all files exist
    for path in [comprehensive_path, summary_path, selected_path]:
        if not path.exists():
            raise FileNotFoundError(f"Required Stage 2 file not found: {path}")
    
    # Load DataFrames
    logger.info("Loading comprehensive analysis...")
    df_comprehensive = pd.read_csv(comprehensive_path)
    
    logger.info("Loading selection summary...")
    df_summary = pd.read_csv(summary_path)
    
    logger.info("Loading selected representatives...")
    df_selected = pd.read_csv(selected_path)
    
    # Data integrity is checked implicitly during visualization
    
    logger.info(f"Stage 2 data loaded successfully:")
    logger.info(f"   All papers: {len(df_comprehensive):,}")
    logger.info(f"   Selected representatives: {len(df_selected):,}")
    logger.info(f"   Topics: {len(df_summary)}")
    
    return df_comprehensive, df_summary, df_selected





 